 <style>
    
 </style>
<div class ="row">
<div class="col-md-12">
                <h4><b>Terms &amp; Conditions</b></h4>
                <div class="content_col  li_box" data-aos="fade-up">        
                <p>Welcome to the Humnafs fashion. In using the service of Humnafs Fashion. you are deemed to have accepted the terms and conditions listed herein.</p>
<p>This document is an electronic record under Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes under applicable Indian laws. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
<p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and terms for access or usage of www.humnafs.com website.</p>
<p>The domain name www.humnafs.com. (hereinafter referred to as ‘Website’) is owned by Miss Anshu Rana with its registered office at 6A/1 second floor , taimoor nagar , New Friends Colony (hereinafter referred to as “Humnafs”).</p>
<p>Your use of the Website, services, Mobile Application and tools are governed by the following terms and conditions (‘Terms of Use’) as applicable. If You transact on the Website, You shall be subject to the policies that are applicable to the Website for such transactions. By mere use of the Website, you shall be contracting with Humnafs and these terms and conditions including the policies constitute your binding obligations with Humnafs.</p>
<p>For the purpose of these Terms of Use, Registered User / Visitor and wherever the context so require ‘You’ shall mean any natural or legal person who has agreed to become a member of the Website by providing Registration Data (as defined hereinafter) while registering on the Website as Registered User using the computer systems of the Website or who has used the Website without becoming a Registered User. The terms ‘We’, ‘Us’, ‘Our’ shall mean Humnafs.</p>
<p>Humnafs may amend these Terms of Use at any time by posting a revised version on the Website. The revised version will be effective at the time we posts it on the Website. You are advised to regularly check for any amendments or updates to the terms and conditions contained in these Terms of Use.</p>
<p><strong>Membership Eligibility</strong></p>
<p>Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are ‘incompetent to contract’ within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website. If you are a minor, i.e. under the age of 18 years, you shall not register as a User of the Website and shall not transact on or use the Website. As a minor if you wish to use or transact on website, such use or transaction may be made by your legal guardian or parents on the Website. Humnafs reserves the right to terminate your membership and/or refuse to provide you with access to the Website if it is brought to our notice or if it is discovered that you are under the age of 18 years or you are not eligible to execute any legal document in personal capacity.</p>
<p><strong>Your Account and Registration Obligations</strong></p>
<p>If You use the Website, You shall be responsible for maintaining the confidentiality of Your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of Your membership on the Website and refuse to provide You with access to the Website.</p>
<p><strong>Communications</strong></p>
<p>When You use the Website or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with You by SMS, email, voice calls or by such other mode of communication, electronic or otherwise. The Registration Data and email ID or Your account details of the third party website through which You register with the Website will be construed as Your ‘designated electronic address’ and Humnafs, Website, other Registered Users, Visitors, third parties and law enforcement agencies will communicate with You on your designated electronic address which will be deemed adequate service of notice / electronic record.</p>
<p><strong>Privacy Policy</strong></p>
<p>Humnafs collects, stores, processes and uses Your information in accordance with our Privacy Policy. By using the Website and/ or by providing your information, you consent to the collection and use of the information you disclose on the Website by Humnafs in accordance with Humnafs’s Privacy Policy which can be read here.</p>
<p><strong>Use of the Website</strong></p>
<p>You shall not host, display, upload, modify, publish, transmit, update or share any information which:<br>
a) Belongs to another person and to which You does not have any right to;<br>
(b) Is grossly harmful, harassing, blasphemous, defamatory, obscene, violent, pornographic, pedophilic, offensive, libelous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, illegal, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to ‘indecent representation of women’ within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986; or soliciting personal information from anyone;</p>
<p>(c) Is misleading in any way;</p>
<p>(d) Involves the transmission of ‘junk mail’, ‘chain letters’, or unsolicited mass mailing or ‘spamming’;</p>
<p>(e) Infringes upon or violates any third party’s rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person’s name, email address, physical address or phone number) or rights of publicity];</p>
<p>(f) Contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);</p>
<p>(g) Tries to gain unauthorized access or exceeds the scope of authorized access to the Website;</p>
<p>(h) Impersonate another person;</p>
<p>(i) Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any Trojan horses, worms, time bombs, cancel bots, Easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;</p>
<p>You shall not use any ‘deep-link’, ‘page-scrape’, ‘robot’, ‘spider’ or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website. You shall not attempt to gain unauthorized access to any portion or feature of the Website, or any other systems or networks connected to the Website or to any server, computer, network, or to any of the services offered on or through the Website, by hacking, password ‘mining’ or any other illegitimate means. We reserve Our right to bar any such activity.</p>
<p>You shall not probe, scan or test the vulnerability of the Website or any network neither connected to the Website nor breach the security or authentication measures on the Website or any network connected to the Website. You may not reverse look-up, trace or seek to trace any information on any other User of or visitor to Website, or any other customer, including any account on the Website not owned by You, to its source, or exploit the Website or any service or information made available or offered by or through the Website, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than Your own information, as provided for by the Website.</p>
<p>You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us including the terms Humnafs, Website, or otherwise engage in any conduct or action that might tarnish the image or reputation, of Humnafs or sellers on platform or otherwise tarnish or dilute any Humnafs’s trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us. You agree that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Website or our systems or networks, or any systems or networks connected to Humnafs.<br>
You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on the Website, or with any other person’s use of the Website.</p>
<p>You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to Us on or through the Website or any service offered on or through the Website. You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity.</p>
<p>You may not use the Website or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of Humnafs and/or others.</p>
<p>You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules thereunder as applicable and as amended from time to time and also all applicable Domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in Force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Sales Tax/VAT, Income Tax, Octroi, Service Tax, Central Excise, Custom Duty, Local Levies) regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase, and sale of products or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force.</p>
<p>Solely to enable Us to use the information You supply Us with, so that we are not violating any rights You might have in Your Information, You agree to grant Us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in Your Information, in any media now known or not currently known, with respect to Your Information. We will only use Your information in accordance with the Terms of Use and Privacy Policy applicable to use of the Website.</p>
<p><strong>Disclaimer of Warranties and Liability</strong></p>
<p>Humnafs and its suppliers, affiliates and service providers provide the Website and services on “as is” basis and without any warranty or condition, express, implied or statutory and specifically disclaim any implied warranties of title, merchantability, fitness for a particular purpose and non-infringement. You expressly agree that your use of the Website is at your risk.</p>
<p>Humnafs does not warrant that this site; information, Content, materials, product (including software) or services included on or otherwise made available to You through the Website; their servers; or electronic communication sent from Us are free of viruses or other harmful components or error free or uninterrupted.</p>
<section class="elementor-section elementor-top-section elementor-element elementor-element-75f77bac elementor-section-boxed elementor-section-height-default elementor-section-height-default sc_fly_static trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="75f77bac" data-element_type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
<div class="elementor-container elementor-column-gap-extended">
<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-6df00861 sc_inner_width_none sc_content_align_inherit sc_layouts_column_icons_position_left sc_fly_static trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="6df00861" data-element_type="column">
<div class="elementor-widget-wrap elementor-element-populated">
<div class="elementor-element elementor-element-682fffa sc_fly_static elementor-widget elementor-widget-text-editor trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="682fffa" data-element_type="widget" data-widget_type="text-editor.default">
<div class="elementor-widget-container">
<p><strong>Payment</strong></p>
<p>While availing any of the payment method(s) available on the Website, we will&nbsp;not be responsible or assume any liability whatsoever in respect to any loss or damage arising directly or indirectly to You due to:</p>
<ol>
<li>Lack of authorization for any transaction(s), or</li>
<li>Exceeding the present limit mutually agreed by You and between ‘Bank(s)’, or</li>
<li>Any payment issues arising out of the transaction, or</li>
<li>Decline of transaction for any other reason(s).</li>
</ol>
<p><strong>All payments made against the purchases/related services on Website by You shall be compulsorily in Indian Rupees acceptable in the Republic of India. The Website will not facilitate transactions in any other form of currency with respect to the purchases made on Website. Humnafs uses a third-party service provider to facilitate and collect payments (‘Payment Facility’) and Humnafs is not liable or responsible for any issue between You and such third-party service provider.</strong></p>
</div>
</div>
</div>
</div>
</div>
</section>
<section class="elementor-section elementor-top-section elementor-element elementor-element-594f5e15 elementor-section-boxed elementor-section-height-default elementor-section-height-default sc_fly_static trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="594f5e15" data-element_type="section">
<div class="elementor-container elementor-column-gap-extended">
<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-5d4b9154 sc_inner_width_none sc_content_align_inherit sc_layouts_column_icons_position_left sc_fly_static trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="5d4b9154" data-element_type="column">
<div class="elementor-widget-wrap elementor-element-populated">
<div class="elementor-element elementor-element-79ec6774 sc_fly_static elementor-widget elementor-widget-spacer trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="79ec6774" data-element_type="widget" data-widget_type="spacer.default">
<div class="elementor-widget-container">
<div class="elementor-spacer">
<div class="elementor-spacer-inner"></div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section class="elementor-section elementor-top-section elementor-element elementor-element-2d8dc980 elementor-section-boxed elementor-section-height-default elementor-section-height-default sc_fly_static trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="2d8dc980" data-element_type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
<div class="elementor-container elementor-column-gap-extended">
<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-46b827c5 sc_inner_width_none sc_content_align_inherit sc_layouts_column_icons_position_left sc_fly_static trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="46b827c5" data-element_type="column">
<div class="elementor-widget-wrap elementor-element-populated">
<div class="elementor-element elementor-element-1a92204b sc_fly_static elementor-widget elementor-widget-text-editor trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="1a92204b" data-element_type="widget" data-widget_type="text-editor.default">
<div class="elementor-widget-container">
<p><strong>Compliance with Laws</strong></p>
<p>Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. Courts at Bangalore shall have exclusive jurisdiction for resolution of any dispute arising out of the use of the Website.</p>
<p>In accordance with Information Technology Act 2000 and rules made there under, the Grievance Officer for the purpose of Your personal sensitive information as governed by the Company Privacy Policy is Mr. Pranjal Rana and can be reached at&nbsp;<u><a href="mailto:support@humnafs.com">support@humnafs.com</a></u>.</p>
<p><strong>General</strong></p>
<p>None of the provisions of the Terms of Use shall be deemed to constitute a partnership or agency between You and Humnafs and You shall have no authority to bind Humnafs in any manner whatsoever nor shall we have any authority to bind you in any manner whatsoever. All the services provided by us shall be as independent contractor and on principal to principal basis.</p>
<p>If any clause of the Terms of Use shall be deemed invalid, void or for any reason unenforceable, such clause shall be deemed severable and shall not affect the validity and enforceability of the remaining clauses of the Terms of Use.</p>
<p>This Terms of Use sets forth the entire understanding and agreement between You and Humnafs with respect to the subject matter hereof.</p>
<p>In Humnafs’s sole discretion, Humnafs may transfer its rights and obligations under this Agreement, assign this Agreement or novate this Agreement without your prior express consent.</p>
<p><strong>Limitation of Liability</strong></p>
<p>In no event shall Humnafs be liable for any special, incidental,&nbsp;indirect or consequential damages of any kind in connection with these terms of use.</p>
</div>
</div>
</div>
</div>
</div>
</section>
                </div>
            </div>

</div>